In [22]:
import pandas as pd
import seaborn as sns
import plotly.express as px
import numpy as np
from sklearn.preprocessing import OrdinalEncoder
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from sklearn.cross_decomposition import PLSRegression

In [23]:
df_path = "C:/Users/nicow/OneDrive/01_job/Technical_Steps/estuaire/data_challenge.csv"
df = pd.read_csv(df_path, sep=";")
df["Date"] = pd.to_datetime(df["Date"], format="%d/%m/%Y")
df["Take-off Time (UTC)"] = pd.to_datetime(
    df["Take-off Time (UTC)"], format="%d/%m/%Y %H:%M"
)
df

,Aircraft,Engine,Role,Registration,Seats,Cargo Capacity (t),Flight Number,Date,Take-off Time (UTC),Origin Airport,Destination Airport,Distance OD (km),Distance Flown (km),CO2 (kgCO2e),Contrails (kgCO2e)
0,A20N,PW1127G-JM,PAX,EC-NFH,186.0,0.0,VY7835,2023-06-15,2023-06-15 16:01:00,EGKK,LEBL,1109.053917,1155.727519,11253.969499,0.000000
1,A20N,PW1127G-JM,PAX,EC-NIJ,186.0,0.0,VY7830,2023-06-15,2023-06-15 05:12:00,LEBL,EGKK,1109.053917,1255.367953,11965.946434,16370.295266
2,A20N,PW1127G-JM,PAX,EC-NCT,186.0,0.0,VY3212,2023-12-31,2023-12-31 10:52:00,LEBL,GCXO,2194.502853,NaN,19808.910939,NaN
3,A20N,PW1127G-JM,PAX,EC-NCF,186.0,0.0,VY6213,2023-10-09,2023-10-09 15:49:00,LEMG,LIRF,1548.024410,1590.238353,14352.387644,41217.801880
4,A321,CFM56-5B3/3,PAX,EC-NLY,220.0,0.0,VY8748,2023-11-02,2023-11-02 13:50:00,EGCC,LEBL,1379.156221,1492.741633,20147.168918,11686.423628
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,A321,V2533-A5,PAX,EC-MOO,220.0,0.0,VY6937,2023-07-28,2023-07-28 13:44:00,LEIB,LFPO,1098.264174,1234.678762,17236.971394,0.000000
19996,A320,V2527-A5,PAX,EC-MEQ,186.0,0.0,VY3293,2023-09-04,2023-09-04 17:18:00,EKCH,EHVK,634.882463,NaN,10097.686470,NaN
19997,A321,V2533-A5,PAX,EC-MQL,220.0,0.0,VY1883,2023-02-13,2023-02-13 20:41:00,EDDB,LEBL,1502.412483,1568.138924,21013.515601,0.000000
19998,A20N,PW1127G-JM,PAX,EC-NDC,186.0,0.0,VY2112,2023-02-25,2023-02-25 18:39:00,LEMG,LEBL,765.966390,876.445651,9263.071031,0.000000
19999,A320,CFM56-5B4/3,PAX,EC-LLM,180.0,0.0,VY8655,2023-03-02,2023-03-02 19:59:00,LKPR,LEBL,1358.028873,1472.992810,17021.347725,0.000000

In [24]:
# drop useless columns
df = df.drop(columns=["Cargo Capacity (t)", "Role"])


# count nan values per column
print(df.isna().sum())
df = df.dropna()

Aircraft                 0
Engine                   0
Registration             0
Seats                    0
Flight Number            0
Date                     0
Take-off Time (UTC)      0
Origin Airport           0
Destination Airport      0
Distance OD (km)         1
Distance Flown (km)    671
CO2 (kgCO2e)             1
Contrails (kgCO2e)     671
dtype: int64

In [25]:
px.histogram(df, x="Contrails (kgCO2e)")

In [26]:
px.histogram(df.where(df["Contrails (kgCO2e)"] != 0), x="Contrails (kgCO2e)")

In [27]:
# count rows where Contrails (kgCO2e) is 0, and get rid of them
print(df[df["Contrails (kgCO2e)"] == 0].shape[0])
print(len(df))
df = df[df["Contrails (kgCO2e)"] != 0]
print(len(df))

12344
19329
6985

In [28]:
# # Calcul de la date minimale
# min_date = df['Date'].min()

# # Conversion des colonnes en minutes depuis la date minimale
# df['Date (minutes)'] = (df['Date'] - min_date).dt.total_seconds() / 60
# df['Take-off Time (minutes)'] = (df['Take-off Time (UTC)'] - min_date).dt.total_seconds() / 60

In [29]:
categorical_features = [
    "Aircraft",
    "Engine",
    "Registration",
    "Flight Number",
    "Origin Airport",
    "Destination Airport",
]
numerical_features = df.columns.difference(categorical_features)


encoder = OrdinalEncoder()
categorical_data = encoder.fit_transform(df[categorical_features])


categorical_data = pd.DataFrame(categorical_data, columns=categorical_features).dropna()


data = pd.concat([df[numerical_features], categorical_data], axis=1).dropna()
data

,CO2 (kgCO2e),Contrails (kgCO2e),Date,Distance Flown (km),Distance OD (km),Seats,Take-off Time (UTC),Aircraft,Engine,Registration,Flight Number,Origin Airport,Destination Airport
1,11965.946434,16370.295266,2023-06-15,1255.367953,1109.053917,186.0,2023-06-15 05:12:00,0.0,5.0,103.0,544.0,46.0,94.0
3,14352.387644,41217.801880,2023-10-09,1590.238353,1548.024410,186.0,2023-10-09 15:49:00,3.0,7.0,46.0,248.0,59.0,47.0
4,20147.168918,11686.423628,2023-11-02,1492.741633,1379.156221,220.0,2023-11-02 13:50:00,3.0,1.0,21.0,565.0,66.0,94.0
10,10632.932103,434360.293772,2023-02-13,787.970150,701.154153,180.0,2023-02-13 20:38:00,3.0,1.0,22.0,531.0,96.0,48.0
13,14932.163157,1518.480424,2023-04-28,1247.983036,1088.665991,180.0,2023-04-28 07:20:00,3.0,1.0,18.0,929.0,40.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6951,7061.216434,61717.662191,2023-01-02,566.307141,453.468536,186.0,2023-01-02 21:13:00,0.0,5.0,107.0,188.0,42.0,48.0
6965,16399.772151,537096.819247,2023-10-01,1405.901790,1241.136244,180.0,2023-10-01 16:30:00,0.0,5.0,118.0,134.0,5.0,48.0
6969,20146.491584,15767.109699,2023-03-22,1807.618967,1645.205998,180.0,2023-03-22 06:02:00,3.0,7.0,42.0,47.0,17.0,44.0
6974,8543.747535,5226.820196,2023-11-29,563.371344,453.468536,180.0,2023-11-29 15:29:00,0.0,5.0,108.0,51.0,40.0,47.0
6976,9869.569902,-1132.225961,2023-05-29,960.570610,898.660945,186.0,2023-05-29 04:53:00,3.0,1.0,39.0,771.0,46.0,76.0

In [30]:
data.describe()

,CO2 (kgCO2e),Contrails (kgCO2e),Date,Distance Flown (km),Distance OD (km),Seats,Take-off Time (UTC),Aircraft,Engine,Registration,Flight Number,Origin Airport,Destination Airport
count,2407.000000,2.407000e+03,2407,2407.000000,2407.000000,2407.000000,2407,2407.000000,2407.000000,2407.000000,2407.000000,2407.000000,2407.000000
mean,15746.860923,4.108165e+04,2023-06-29 00:32:18.346489344,1361.944551,1255.274886,188.009971,2023-06-29 13:07:35.471541248,2.523473,4.874533,64.118405,464.562111,45.444121,52.022850
min,7061.216434,-7.379588e+05,2023-01-01 00:00:00,456.090348,0.000000,144.000000,2023-01-01 05:19:00,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000
25%,12100.541097,-1.635407e+03,2023-04-09 00:00:00,958.778237,854.821215,180.000000,2023-04-09 07:14:30,2.000000,2.000000,33.000000,173.000000,35.000000,36.000000
50%,14780.329054,5.309812e+02,2023-06-09 00:00:00,1268.656798,1109.053917,186.000000,2023-06-09 04:59:00,3.000000,5.000000,65.000000,474.000000,40.000000,48.000000
75%,17953.711087,2.732005e+04,2023-10-04 00:00:00,1603.627850,1485.689825,186.000000,2023-10-04 07:14:30,3.000000,7.000000,94.000000,757.000000,59.000000,68.000000
max,43357.136145,2.150571e+06,2023-12-31 00:00:00,4151.327430,3849.304846,230.000000,2023-12-31 17:22:00,4.000000,8.000000,125.000000,972.000000,97.000000,109.000000
std,5185.960909,1.520994e+05,NaN,529.363474,518.541106,18.068676,NaN,1.313721,2.581998,35.540999,308.793576,22.853488,24.883834

In [31]:
# sns.pairplot(data)

In [32]:
data_pre_pca = data.drop(columns=["Contrails (kgCO2e)"])
n_components = len(data_pre_pca.columns)
pca = PCA(n_components=n_components)


x_norm = ((data_pre_pca - data_pre_pca.mean()) / data_pre_pca.std()).values


data_pca = pca.fit_transform(x_norm)



data["PC1"] = data_pca[:, 0]


data["PC2"] = data_pca[:, 1]


data["PC3"] = data_pca[:, 2]



# 3D PCA plot


fig0 = px.scatter_3d(
    data,

    x="PC1",
    y="PC2",
    z="PC3",
    height=800,
    width=800,
    color="Contrails (kgCO2e)",
    color_continuous_scale=px.colors.diverging.Portland,
).update_traces(marker=dict(size=2))


fig0.show()


# 2D PCA plot


fig1 = px.scatter(
    data,

    x="PC1",
    y="PC2",
    color="Contrails (kgCO2e)",
    color_continuous_scale=px.colors.diverging.Portland,
)



loadings = pca.components_.T * np.sqrt(pca.explained_variance_)



for i, feature in enumerate(data_pre_pca.columns[:-3]):

    print(feature)

    fig1.add_annotation(
        ax=0,
        ay=0,
        axref="x",
        ayref="y",
        x=loadings[i, 0],
        y=loadings[i, 1],
        showarrow=True,
        arrowsize=2,
        arrowhead=2,
        xanchor="right",
        yanchor="top",
    )


    fig1.add_annotation(
        x=loadings[i, 0],
        y=loadings[i, 1],
        ax=0,
        ay=0,
        xanchor="center",
        yanchor="bottom",
        text=feature,
        yshift=5,
    )



fig1.show()

C:\Users\nicow\AppData\Local\Temp\ipykernel_21908\3531610547.py:6: PerformanceWarning:

Adding/subtracting object-dtype array to DatetimeArray not vectorized.

C:\Users\nicow\AppData\Local\Temp\ipykernel_21908\3531610547.py:6: PerformanceWarning:

Adding/subtracting object-dtype array to DatetimeArray not vectorized.

CO2 (kgCO2e)
Date
Distance Flown (km)
Distance OD (km)
Seats
Take-off Time (UTC)
Aircraft
Engine
Registration

# PLS

In [33]:
correlation = data.corr()
correlation["Contrails (kgCO2e)"].apply(lambda x: abs(x)).sort_values(
    ascending=False
).head(12)

Contrails (kgCO2e)     1.000000
CO2 (kgCO2e)           0.123096
Distance Flown (km)    0.112556
PC1                    0.111199
Distance OD (km)       0.084733
Seats                  0.062356
Aircraft               0.018799
Destination Airport    0.018436
Take-off Time (UTC)    0.017095
Engine                 0.016981
Date                   0.016506
Flight Number          0.011081
Name: Contrails (kgCO2e), dtype: float64

Right to use CO2?

In [34]:
feature_selection_list = [
    "Distance Flown (km)",
    "Distance OD (km)",
    "Seats",
    "Aircraft",
    "Destination Airport",
    "Take-off Time (UTC)",
    "Engine",
    "Date",
]

In [35]:
data["Contrails (kgCO2e)"].describe()

count    2.407000e+03
mean     4.108165e+04
std      1.520994e+05
min     -7.379588e+05
25%     -1.635407e+03
50%      5.309812e+02
75%      2.732005e+04
max      2.150571e+06
Name: Contrails (kgCO2e), dtype: float64

In [36]:
y = data["Contrails (kgCO2e)"]
# normalize y and apply log transformation
y = np.log(y - y.min() + 1)

pls = PLSRegression(n_components=3)
pls.fit(x_norm, y)

data["PLS_PC1"] = pls.x_scores_[:, 0]
data["PLS_PC2"] = pls.x_scores_[:, 1]
data["PLS_PC3"] = pls.x_scores_[:, 2]

# plotting the loadings
loadings = pls.x_loadings_
fig = px.scatter(
    data,
    x="PLS_PC1",
    y="PLS_PC2",
    color="Contrails (kgCO2e)",
    color_continuous_scale=px.colors.diverging.Portland,
)

for i, feature in enumerate(feature_selection_list):
    fig.add_annotation(
        ax=0,
        ay=0,
        axref="x",
        ayref="y",
        x=loadings[i, 0],
        y=loadings[i, 1],
        showarrow=True,
        arrowsize=2,
        arrowhead=2,
        xanchor="right",
        yanchor="top",
    )
    fig.add_annotation(
        x=loadings[i, 0],
        y=loadings[i, 1],
        ax=0,
        ay=0,
        xanchor="center",
        yanchor="bottom",
        text=feature,
        yshift=5,
    )
fig.show()

In [37]:
# linear regression y = f(PLS_PC1)
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


X = data[["PLS_PC1"]].values
y = data["Contrails (kgCO2e)"].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
reg = LinearRegression().fit(X_train, y_train)
y_pred = reg.predict(X)
fig = px.scatter(
    data,
    x="PLS_PC1",
    y="Contrails (kgCO2e)",
    color="Contrails (kgCO2e)",
    color_continuous_scale=px.colors.diverging.Portland,
)
fig.add_scatter(
    x=data["PLS_PC1"],
    y=y_pred,
    mode="lines",
    line=dict(color="red", width=2),
    name="Regression Line",
)
fig.update_layout(
    title="Linear Regression of y = f(PLS_PC1)",
    xaxis_title="PLS_PC1",
    yaxis_title="Contrails (kgCO2e)",
)
fig.show()
# print r squared and mean squared error
print("R^2: ", reg.score(X_test, y_test))
print("Mean Squared Error: ", np.mean((y_pred - y) ** 2))

R^2:  -0.011013782902183245
Mean Squared Error:  22836833855.507996

# XGBoost

In [38]:
input_features = [
    "Date",
    "Distance Flown (km)",
    "Distance OD (km)",
    "Seats",
    "Take-off Time (UTC)",
    "Aircraft",
    "Engine",
    "Registration",
    "Flight Number",
    "Origin Airport",
    "Destination Airport",
]

# Calcul de la date minimale
min_date = data["Date"].min()

# Conversion des colonnes en minutes depuis la date minimale
data["Date"] = (data["Date"] - min_date).dt.total_seconds() / 3600 / 24
data["Take-off Time (UTC)"] = (
    (data["Take-off Time (UTC)"] - min_date).dt.total_seconds() / 3600 / 24
)

In [39]:
# using xgboost for regression on Contrails (kgCO2e), using data[feature_selection_list] as features
# we use cross validation to find the best parameters
from xgboost import XGBRegressor
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split

from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform, randint


X = data[input_features].values
y = data["Contrails (kgCO2e)"].values
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
# define the model
model = XGBRegressor()
# define the parameter grid for RandomizedSearchCV
param_dist = {
    "n_estimators": randint(50, 200),
    "max_depth": randint(2, 10),
    "min_child_weight": randint(1, 10),
    "subsample": uniform(0.5, 0.5),
    "colsample_bytree": uniform(0.5, 0.5),
    "gamma": uniform(0, 5),
    "reg_alpha": uniform(0, 1),
    "reg_lambda": uniform(0, 1),
}
# perform Randomized search with cross validation

grid_search = RandomizedSearchCV(
    model,
    param_distributions=param_dist,
    n_iter=10,
    scoring="neg_mean_squared_error",
    cv=KFold(n_splits=5, shuffle=True, random_state=42),
    verbose=1,
    n_jobs=-1,
)
grid_search.fit(X_train, y_train)
# print best parameters
print("Best parameters: ", grid_search.best_params_)
# print best score
print("Best score: ", grid_search.best_score_)
# fit the model with the best parameters
model = grid_search.best_estimator_
model.fit(X_train, y_train)
# make predictions on the test set
y_pred = model.predict(X_test)
# calculate the mean squared error and r squared
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
print("Mean squared error: ", mse)
print("Root mean squared error: ", rmse)
print("R squared: ", r2)

# plot feature importance
importances = model.feature_importances_
indices = np.argsort(importances)[::-1]
fig = px.bar(
    y=importances[indices],
    x=data[input_features].columns[indices],
    labels={"x": "Feature", "y": "Importance"},
    title="Feature Importance",
)
fig.update_traces(marker_color="blue")
fig.update_layout(xaxis_tickangle=-45)
fig.show()

Fitting 5 folds for each of 10 candidates, totalling 50 fits
Best parameters:  {'colsample_bytree': np.float64(0.9495092696004115), 'gamma': np.float64(1.6788262954735038), 'max_depth': 2, 'min_child_weight': 8, 'n_estimators': 83, 'reg_alpha': np.float64(0.3733553898090237), 'reg_lambda': np.float64(0.46062215638215065), 'subsample': np.float64(0.7855460746120042)}
Best score:  -24307368318.524372
Mean squared error:  21622068108.170048
Root mean squared error:  147044.44262932907
R squared:  -0.08516413720452798

In [40]:
# save the model
import joblib

joblib.dump(model, "trained_models/xgboost_model.pkl")

['trained_models/xgboost_model.pkl']

In [41]:
# Same with random forest regressor
from sklearn.ensemble import RandomForestRegressor

# define the model
model = RandomForestRegressor()
# define the parameter grid for RandomizedSearchCV
param_dist = {
    "n_estimators": randint(50, 200),
    "max_depth": randint(2, 10),
    "min_samples_split": randint(2, 10),
    "min_samples_leaf": randint(1, 10),
    "max_features": ["auto", "sqrt"],
}
# perform Randomized search with cross validation
grid_search = RandomizedSearchCV(
    model,
    param_distributions=param_dist,
    n_iter=10,
    scoring="neg_mean_squared_error",
    cv=KFold(n_splits=5, shuffle=True, random_state=42),
    verbose=1,
    n_jobs=-1,
)
grid_search.fit(X_train, y_train)
print("Best parameters: ", grid_search.best_params_)
print("Best score: ", grid_search.best_score_)
# fit the model with the best parameters
model = grid_search.best_estimator_
model.fit(X_train, y_train)
# make predictions on the test set
y_pred = model.predict(X_test)
# calculate the mean squared error and r squared
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
print("Mean squared error: ", mse)
print("Root mean squared error: ", rmse)
print("R squared: ", r2)
# plot feature importance
importances = model.feature_importances_
indices = np.argsort(importances)[::-1]
fig = px.bar(
    y=importances[indices],
    x=data[input_features].columns[indices],
    labels={"x": "Feature", "y": "Importance"},
    title="Feature Importance",
)
fig.update_traces(marker_color="blue")
fig.update_layout(xaxis_tickangle=-45)
fig.show()

Fitting 5 folds for each of 10 candidates, totalling 50 fits

c:\Users\nicow\OneDrive\01_job\Technical_Steps\estuaire\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:


35 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
35 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\nicow\OneDrive\01_job\Technical_Steps\estuaire\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\nicow\OneDrive\01_job\Technical_Steps\estuaire\.venv\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "c:\Users\nicow\OneDrive\01_job\Technical_Steps\estuaire\.venv\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\nicow\OneDrive\01_job\Technical_Steps\estuaire\.venv\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.


c:\Users\nicow\OneDrive\01_job\Technical_Steps\estuaire\.venv\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning:

One or more of the test scores are non-finite: [-2.33070990e+10 -2.34282198e+10             nan             nan
             nan             nan             nan -2.34239877e+10
             nan             nan]

Best parameters:  {'max_depth': 8, 'max_features': 'sqrt', 'min_samples_leaf': 6, 'min_samples_split': 3, 'n_estimators': 146}
Best score:  -23307098953.026054
Mean squared error:  20432356126.88225
Root mean squared error:  142941.79279301857
R squared:  -0.025455104320285526

# Neural Network Regressor

In [ ]:
from nn_model import NNRegressor
from torch.utils.data import DataLoader, TensorDataset
import torch
from sklearn.model_selection import train_test_split

n_dimension = len(data[input_features].columns)
model = NNRegressor(nb_dimensions=n_dimension)
X = data[input_features].values
X_norm = ((X - X.mean()) / X.std()).astype(np.float32)
y = data["Contrails (kgCO2e)"].values
X_train, X_test, y_train, y_test = train_test_split(
    X_norm, y, test_size=0.2, random_state=42
)
tensor_x_train = torch.tensor(X_train, dtype=torch.float32)
tensor_y_train = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)
train_dataset = TensorDataset(tensor_x_train, tensor_y_train)
train_dataloader = DataLoader(train_dataset, batch_size=32, shuffle=True)
tensor_x_test = torch.tensor(X_test, dtype=torch.float32)
tensor_y_test = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)
test_dataset = TensorDataset(tensor_x_test, tensor_y_test)
test_dataloader = DataLoader(test_dataset, batch_size=32, shuffle=False)

n_epochs = 1000
train_loss_list = []
test_loss_list = []
for epoch in range(n_epochs):
    train_loss = model.train(train_dataloader)
    test_loss = model.test(test_dataloader)
    train_loss_list.append(train_loss)
    test_loss_list.append(test_loss)
    print(f"Epoch {epoch+1}, Train loss: {train_loss}, Test loss: {test_loss}")

# plot the train and test loss
px.scatter(x=range(n_epochs), y=train_loss_list, title="Train loss").add_scatter(
    y=test_loss_list, name="Test loss", mode="markers"
).show()

# make predictions on the test set and print rmse and r squared
y_pred = model.forward(tensor_x_test).detach().numpy()
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
print("Mean squared error: ", mse)
print("Root mean squared error: ", rmse)
print("R squared: ", r2)

Epoch 1, Train loss: 25199102730.491802, Test loss: 22998135008.0
Epoch 2, Train loss: 25011742069.5082, Test loss: 22317061536.0
Epoch 3, Train loss: 24311700219.803265, Test loss: 20810066464.0
Epoch 4, Train loss: 23487703474.36066, Test loss: 20450026176.0
Epoch 5, Train loss: 23415913864.39344, Test loss: 20751974976.0
Epoch 6, Train loss: 27849729760.524582, Test loss: 20404342976.0
Epoch 7, Train loss: 23340306289.311474, Test loss: 20583793120.0
Epoch 8, Train loss: 24032948096.000004, Test loss: 20356612704.0
Epoch 9, Train loss: 23338025876.983604, Test loss: 20596486656.0
Epoch 10, Train loss: 23402285230.163925, Test loss: 20460273920.0
Epoch 11, Train loss: 23321898439.34427, Test loss: 20690150976.0
Epoch 12, Train loss: 24287783251.93443, Test loss: 20673471680.0
Epoch 13, Train loss: 23561552975.7377, Test loss: 20498375488.0
Epoch 14, Train loss: 24370864795.278698, Test loss: 20401031648.0
Epoch 15, Train loss: 23307744730.2295, Test loss: 20542264768.0
Epoch 16, Train loss: 23416218166.557373, Test loss: 20569704064.0
Epoch 17, Train loss: 23599514057.44262, Test loss: 20486818720.0
Epoch 18, Train loss: 23328072179.40984, Test loss: 20514670720.0
Epoch 19, Train loss: 23391681460.459015, Test loss: 20503381760.0
Epoch 20, Train loss: 23367262833.311474, Test loss: 20517516000.0
Epoch 21, Train loss: 32904724639.475407, Test loss: 20485405856.0
Epoch 22, Train loss: 23329029694.950817, Test loss: 20599351936.0
Epoch 23, Train loss: 23404502987.540985, Test loss: 20479931776.0
Epoch 24, Train loss: 23271681428.98361, Test loss: 20616736032.0
Epoch 25, Train loss: 23341464621.11475, Test loss: 20459846144.0
Epoch 26, Train loss: 23419693794.62294, Test loss: 20589984704.0
Epoch 27, Train loss: 23503718853.2459, Test loss: 20583583616.0
Epoch 28, Train loss: 23451071609.70492, Test loss: 20556442720.0
Epoch 29, Train loss: 23603947039.475407, Test loss: 20450721472.0
Epoch 30, Train loss: 23926056766.950813, Test loss: 20567577600.0
Epoch 31, Train loss: 23338615627.54098, Test loss: 20585707232.0
Epoch 32, Train loss: 23365501276.327866, Test loss: 20471974112.0
Epoch 33, Train loss: 23333541879.60656, Test loss: 20454618112.0
Epoch 34, Train loss: 23293165452.590164, Test loss: 20424290464.0
Epoch 35, Train loss: 23534794334.426235, Test loss: 20582102880.0
Epoch 36, Train loss: 23362499189.508198, Test loss: 20562483520.0
Epoch 37, Train loss: 23332004662.557377, Test loss: 20485756800.0
Epoch 38, Train loss: 23346830659.14754, Test loss: 20421445440.0
Epoch 39, Train loss: 23430290967.08197, Test loss: 20435437408.0
Epoch 40, Train loss: 24109575499.540985, Test loss: 20442484992.0
Epoch 41, Train loss: 23419203770.754097, Test loss: 20569841568.0
Epoch 42, Train loss: 23335456925.377045, Test loss: 20652151360.0
Epoch 43, Train loss: 26509205873.311485, Test loss: 20558590720.0
Epoch 44, Train loss: 23484463737.70492, Test loss: 20668378400.0
Epoch 45, Train loss: 23304341260.590168, Test loss: 20447464832.0
Epoch 46, Train loss: 23260105570.62295, Test loss: 20483541664.0
Epoch 47, Train loss: 23421795955.40983, Test loss: 20524128000.0
Epoch 48, Train loss: 23274320751.21311, Test loss: 20434353920.0
Epoch 49, Train loss: 23309573187.14753, Test loss: 20682200032.0
Epoch 50, Train loss: 23566208402.885258, Test loss: 20622203456.0
Epoch 51, Train loss: 23306782296.13115, Test loss: 20477129984.0
Epoch 52, Train loss: 23427406025.442623, Test loss: 20406511424.0
Epoch 53, Train loss: 23407300612.196724, Test loss: 20673094240.0
Epoch 54, Train loss: 23659336126.95082, Test loss: 20463652768.0
Epoch 55, Train loss: 23518513865.442627, Test loss: 20620772608.0
Epoch 56, Train loss: 23347256374.557377, Test loss: 20618763456.0
Epoch 57, Train loss: 23396512660.983597, Test loss: 20429452160.0
Epoch 58, Train loss: 23442874762.491795, Test loss: 20495902656.0
Epoch 59, Train loss: 23315689421.639355, Test loss: 20498770144.0
Epoch 60, Train loss: 23304020450.622944, Test loss: 20439113664.0
Epoch 61, Train loss: 23446777558.03279, Test loss: 20428116704.0
Epoch 62, Train loss: 23311263278.163925, Test loss: 20511347840.0
Epoch 63, Train loss: 23308561240.13114, Test loss: 20651652736.0
Epoch 64, Train loss: 23295729909.50821, Test loss: 20675034752.0
Epoch 65, Train loss: 23331411147.54098, Test loss: 20492766016.0
Epoch 66, Train loss: 23406273317.770493, Test loss: 20487711360.0
Epoch 67, Train loss: 23812594822.295074, Test loss: 20476828256.0
Epoch 68, Train loss: 23518033588.45902, Test loss: 20461418048.0
Epoch 69, Train loss: 23246422326.55739, Test loss: 20720246304.0
Epoch 70, Train loss: 23445059248.262295, Test loss: 20704527040.0
Epoch 71, Train loss: 23316188942.68852, Test loss: 20487917888.0
Epoch 72, Train loss: 23348705099.54098, Test loss: 20593657600.0
Epoch 73, Train loss: 23357078320.262302, Test loss: 20480985920.0
Epoch 74, Train loss: 23358670140.852463, Test loss: 20712012608.0
Epoch 75, Train loss: 23481623428.19672, Test loss: 20510464640.0
Epoch 76, Train loss: 23291221323.540985, Test loss: 20517063808.0
Epoch 77, Train loss: 24177730815.999996, Test loss: 20401720224.0
Epoch 78, Train loss: 23278940684.59016, Test loss: 20536795680.0
Epoch 79, Train loss: 23414418251.540977, Test loss: 20490591552.0
Epoch 80, Train loss: 23447516671.999996, Test loss: 20561970176.0
Epoch 81, Train loss: 23268941307.80328, Test loss: 20495697152.0
Epoch 82, Train loss: 23302059419.27869, Test loss: 20571859744.0
Epoch 83, Train loss: 23273135267.672134, Test loss: 20502405856.0
Epoch 84, Train loss: 23288754914.622948, Test loss: 20456254784.0
Epoch 85, Train loss: 23370071191.081974, Test loss: 20530800352.0
Epoch 86, Train loss: 23254923096.13114, Test loss: 20664805856.0
Epoch 87, Train loss: 23605751407.213127, Test loss: 20633806784.0
Epoch 88, Train loss: 23330359535.21312, Test loss: 20517770528.0
Epoch 89, Train loss: 23424247967.475407, Test loss: 20530828672.0
Epoch 90, Train loss: 23226118339.14754, Test loss: 20542947616.0
Epoch 91, Train loss: 23318968628.45902, Test loss: 20476862464.0
Epoch 92, Train loss: 23263325737.96722, Test loss: 20524042944.0
Epoch 93, Train loss: 23504219568.26229, Test loss: 20491523680.0
Epoch 94, Train loss: 23284574132.45901, Test loss: 20731865600.0
Epoch 95, Train loss: 23354191219.40984, Test loss: 20477556800.0
Epoch 96, Train loss: 23289367833.18033, Test loss: 20625242592.0
Epoch 97, Train loss: 23248987091.93443, Test loss: 20681289824.0
Epoch 98, Train loss: 23277154574.688522, Test loss: 20636981152.0
Epoch 99, Train loss: 23398037480.918034, Test loss: 20576892736.0
Epoch 100, Train loss: 23228533401.18033, Test loss: 20535202400.0
Epoch 101, Train loss: 23370473820.327873, Test loss: 20728319648.0
Epoch 102, Train loss: 23244215967.475407, Test loss: 20489420960.0
Epoch 103, Train loss: 23352808481.57377, Test loss: 20435986080.0
Epoch 104, Train loss: 23183604704.524593, Test loss: 20529138560.0
Epoch 105, Train loss: 23278143271.868855, Test loss: 20651944544.0
Epoch 106, Train loss: 23546773115.80328, Test loss: 20531625760.0
Epoch 107, Train loss: 23194097789.90164, Test loss: 20547378528.0
Epoch 108, Train loss: 23464512272.78688, Test loss: 20493101376.0
Epoch 109, Train loss: 23616030411.540977, Test loss: 20540651232.0
Epoch 110, Train loss: 23194658093.11475, Test loss: 20648716736.0
Epoch 111, Train loss: 23310022087.34426, Test loss: 20622841216.0
Epoch 112, Train loss: 23227281387.016396, Test loss: 20619890816.0
Epoch 113, Train loss: 23412607232.0, Test loss: 20537227968.0
Epoch 114, Train loss: 23243885752.655746, Test loss: 20607222816.0
Epoch 115, Train loss: 23180331333.2459, Test loss: 20767323808.0
Epoch 116, Train loss: 23346842997.5082, Test loss: 20739195968.0
Epoch 117, Train loss: 23203144466.885246, Test loss: 20625692032.0
Epoch 118, Train loss: 23218893471.47541, Test loss: 20589198944.0
Epoch 119, Train loss: 23241088356.721313, Test loss: 20662484096.0
Epoch 120, Train loss: 23214784480.52459, Test loss: 20665232384.0
Epoch 121, Train loss: 23227379141.245903, Test loss: 20549868832.0
Epoch 122, Train loss: 28764240023.08197, Test loss: 20638798944.0
Epoch 123, Train loss: 23200318927.737705, Test loss: 20654863360.0
Epoch 124, Train loss: 23182256535.081966, Test loss: 20591865312.0
Epoch 125, Train loss: 24121257453.11475, Test loss: 20555922208.0
Epoch 126, Train loss: 23892579304.91803, Test loss: 20434770880.0
Epoch 127, Train loss: 23267005960.39343, Test loss: 20391113952.0
Epoch 128, Train loss: 23171850260.9836, Test loss: 20537625120.0
Epoch 129, Train loss: 23161450323.934433, Test loss: 20454203008.0
Epoch 130, Train loss: 23196359212.065575, Test loss: 20483134560.0
Epoch 131, Train loss: 23229919303.34426, Test loss: 20576940768.0
Epoch 132, Train loss: 23248796403.409832, Test loss: 20677351808.0
Epoch 133, Train loss: 23334512875.016384, Test loss: 20731805152.0
Epoch 134, Train loss: 24174891566.163937, Test loss: 20484761216.0
Epoch 135, Train loss: 23250380871.344257, Test loss: 20808183424.0
Epoch 136, Train loss: 23257671350.557384, Test loss: 20692572000.0
Epoch 137, Train loss: 23413199074.62296, Test loss: 20550355168.0
Epoch 138, Train loss: 23180829752.655735, Test loss: 20591243616.0
Epoch 139, Train loss: 24402841650.36066, Test loss: 20532504640.0
Epoch 140, Train loss: 23685687784.918045, Test loss: 20536433728.0
Epoch 141, Train loss: 23148890235.803276, Test loss: 20704236128.0
Epoch 142, Train loss: 23167371448.655743, Test loss: 20747193888.0
Epoch 143, Train loss: 23498585142.55739, Test loss: 20689291328.0
Epoch 144, Train loss: 23218923809.573772, Test loss: 20506510016.0
Epoch 145, Train loss: 26745337048.13115, Test loss: 20402344544.0
Epoch 146, Train loss: 23224115976.39344, Test loss: 20670458432.0
Epoch 147, Train loss: 23232530660.721317, Test loss: 20446802336.0
Epoch 148, Train loss: 23233180369.83607, Test loss: 20631367776.0
Epoch 149, Train loss: 23241797350.81968, Test loss: 20505155552.0
Epoch 150, Train loss: 23144318821.770493, Test loss: 20518914720.0
Epoch 151, Train loss: 23210508153.704918, Test loss: 20585649120.0
Epoch 152, Train loss: 23168946520.13115, Test loss: 20518013696.0
Epoch 153, Train loss: 23123131508.459015, Test loss: 20609337120.0
Epoch 154, Train loss: 24573807112.393448, Test loss: 20594122432.0
Epoch 155, Train loss: 23161568428.065567, Test loss: 20576687872.0
Epoch 156, Train loss: 23267672458.491795, Test loss: 20551993216.0
Epoch 157, Train loss: 23182916171.540977, Test loss: 20479961152.0
Epoch 158, Train loss: 23092625044.983612, Test loss: 20554937984.0
Epoch 159, Train loss: 23159654060.065575, Test loss: 20539609984.0
Epoch 160, Train loss: 23595237038.163933, Test loss: 20498369248.0
Epoch 161, Train loss: 23151203518.950825, Test loss: 20980147392.0
Epoch 162, Train loss: 23218976814.16394, Test loss: 20792965920.0
Epoch 163, Train loss: 23133911071.475403, Test loss: 20581846880.0
Epoch 164, Train loss: 23041228515.672134, Test loss: 20967093376.0
Epoch 165, Train loss: 23144598005.508198, Test loss: 20642266624.0
Epoch 166, Train loss: 23066586121.44263, Test loss: 20615130112.0
Epoch 167, Train loss: 23061195148.590176, Test loss: 20733625920.0
Epoch 168, Train loss: 23247244451.672134, Test loss: 20623630784.0
Epoch 169, Train loss: 23336228335.21312, Test loss: 20444053184.0
Epoch 170, Train loss: 23404629390.688522, Test loss: 20533167008.0
Epoch 171, Train loss: 23829733229.11475, Test loss: 20362473984.0
Epoch 172, Train loss: 22994058077.901638, Test loss: 20761692064.0
Epoch 173, Train loss: 23153153355.540977, Test loss: 20588127328.0
Epoch 174, Train loss: 23021652158.95082, Test loss: 20713122880.0
Epoch 175, Train loss: 23107778434.88525, Test loss: 20685488096.0
Epoch 176, Train loss: 23148107725.63935, Test loss: 20639699968.0
Epoch 177, Train loss: 23106743241.44263, Test loss: 20479269216.0
Epoch 178, Train loss: 23118132001.573772, Test loss: 20557118144.0
Epoch 179, Train loss: 23124243319.60656, Test loss: 20467954048.0
Epoch 180, Train loss: 26849730161.311478, Test loss: 20503712992.0
Epoch 181, Train loss: 26756831089.311474, Test loss: 20964790368.0
Epoch 182, Train loss: 23068100326.81968, Test loss: 20641187328.0
Epoch 183, Train loss: 23158390750.426243, Test loss: 20461608672.0
Epoch 184, Train loss: 23236121180.32786, Test loss: 20458504032.0
Epoch 185, Train loss: 23534551144.91803, Test loss: 20565218944.0
Epoch 186, Train loss: 23039249525.508198, Test loss: 20703533024.0
Epoch 187, Train loss: 23224386956.590157, Test loss: 20918895712.0
Epoch 188, Train loss: 23230755674.229515, Test loss: 20467687456.0
Epoch 189, Train loss: 22986181254.295086, Test loss: 20388825632.0
Epoch 190, Train loss: 23509485307.80327, Test loss: 20602250816.0
Epoch 191, Train loss: 23172886230.032784, Test loss: 20765951168.0
Epoch 192, Train loss: 23739305232.78688, Test loss: 20638544544.0
Epoch 193, Train loss: 23032466850.622944, Test loss: 20478346464.0
Epoch 194, Train loss: 23021849230.688526, Test loss: 20523377792.0
Epoch 195, Train loss: 23571777943.081963, Test loss: 20612923904.0
Epoch 196, Train loss: 23178236709.77049, Test loss: 20652657888.0
Epoch 197, Train loss: 23010470154.4918, Test loss: 20508620320.0
Epoch 198, Train loss: 23874034455.081955, Test loss: 20492767840.0
Epoch 199, Train loss: 23196096956.852455, Test loss: 20641967776.0
Epoch 200, Train loss: 23089158828.06557, Test loss: 20932517504.0
Epoch 201, Train loss: 22975910807.081966, Test loss: 20553067456.0
Epoch 202, Train loss: 22989962141.37705, Test loss: 20579308864.0
Epoch 203, Train loss: 23303957096.91803, Test loss: 20567422176.0
Epoch 204, Train loss: 23006473585.311474, Test loss: 20437579328.0
Epoch 205, Train loss: 23005621751.606556, Test loss: 20498269056.0
Epoch 206, Train loss: 22976667047.868855, Test loss: 20651397120.0
Epoch 207, Train loss: 22944195500.065575, Test loss: 20617980032.0
Epoch 208, Train loss: 22956941339.278687, Test loss: 20545944704.0
Epoch 209, Train loss: 22952960889.70491, Test loss: 20485409952.0
Epoch 210, Train loss: 24639778283.01639, Test loss: 20454345152.0
Epoch 211, Train loss: 23783052993.049175, Test loss: 20518709760.0
Epoch 212, Train loss: 22952157775.737705, Test loss: 20525993056.0
Epoch 213, Train loss: 22929474547.40984, Test loss: 20559169632.0
Epoch 214, Train loss: 22974461641.44262, Test loss: 20680231040.0
Epoch 215, Train loss: 22937921510.81966, Test loss: 20469294592.0
Epoch 216, Train loss: 23535984069.245907, Test loss: 20512799008.0
Epoch 217, Train loss: 23028144581.245903, Test loss: 20663097920.0
Epoch 218, Train loss: 22986160734.426235, Test loss: 20521518240.0
Epoch 219, Train loss: 22930978513.836063, Test loss: 20689935296.0
Epoch 220, Train loss: 24585998088.393436, Test loss: 20416389184.0
Epoch 221, Train loss: 22918648458.491806, Test loss: 20864602944.0
Epoch 222, Train loss: 22994745088.0, Test loss: 20434018048.0
Epoch 223, Train loss: 22942942654.950817, Test loss: 20687507360.0
Epoch 224, Train loss: 23025207661.114758, Test loss: 20561419200.0
Epoch 225, Train loss: 23177321675.540993, Test loss: 20992430688.0
Epoch 226, Train loss: 22999337923.147537, Test loss: 20415137312.0
Epoch 227, Train loss: 22825109373.901638, Test loss: 20457334208.0
Epoch 228, Train loss: 22981591833.180317, Test loss: 20696723104.0
Epoch 229, Train loss: 23183486044.327877, Test loss: 20810196992.0
Epoch 230, Train loss: 22835309889.04918, Test loss: 20652559136.0
Epoch 231, Train loss: 23053137000.91804, Test loss: 20538178144.0
Epoch 232, Train loss: 22857035137.049168, Test loss: 20624309984.0
Epoch 233, Train loss: 23040666363.80328, Test loss: 20436662880.0
Epoch 234, Train loss: 22979035910.295082, Test loss: 20447447584.0
Epoch 235, Train loss: 23064212060.32786, Test loss: 20728947264.0
Epoch 236, Train loss: 36947864340.98361, Test loss: 20384007520.0
Epoch 237, Train loss: 22854407235.147537, Test loss: 20407894720.0
Epoch 238, Train loss: 23101108467.409836, Test loss: 20615295776.0
Epoch 239, Train loss: 23147361380.72131, Test loss: 20590196768.0
Epoch 240, Train loss: 23036107014.295086, Test loss: 20571867040.0
Epoch 241, Train loss: 22788095949.63934, Test loss: 20354184256.0
Epoch 242, Train loss: 22787126926.688526, Test loss: 20681197024.0
Epoch 243, Train loss: 23117250371.14755, Test loss: 20409945120.0
Epoch 244, Train loss: 22787430353.836056, Test loss: 20673566304.0
Epoch 245, Train loss: 22801177121.573765, Test loss: 20489316672.0
Epoch 246, Train loss: 23449030261.5082, Test loss: 20553354496.0
Epoch 247, Train loss: 22820212798.950832, Test loss: 20808478368.0
Epoch 248, Train loss: 22998943311.737713, Test loss: 20422260064.0
Epoch 249, Train loss: 22931605042.360653, Test loss: 20662306272.0
Epoch 250, Train loss: 22832927340.065586, Test loss: 20679856160.0
Epoch 251, Train loss: 22816808265.44262, Test loss: 20541633184.0
Epoch 252, Train loss: 22916349601.573772, Test loss: 20810521120.0
Epoch 253, Train loss: 22841157615.213116, Test loss: 20587608800.0
Epoch 254, Train loss: 22814232563.40983, Test loss: 20394896160.0
Epoch 255, Train loss: 22884048270.68853, Test loss: 20727698560.0
Epoch 256, Train loss: 22760215280.262295, Test loss: 20468785952.0
Epoch 257, Train loss: 22851349709.639343, Test loss: 20602128672.0
Epoch 258, Train loss: 22942108799.999996, Test loss: 20608591680.0
Epoch 259, Train loss: 22824449622.032787, Test loss: 20551190144.0
Epoch 260, Train loss: 22809924339.40984, Test loss: 20637747200.0
Epoch 261, Train loss: 25204958482.88525, Test loss: 20435029024.0
Epoch 262, Train loss: 22834546210.62295, Test loss: 20599768320.0
Epoch 263, Train loss: 22726826319.73771, Test loss: 20424470432.0
Epoch 264, Train loss: 22812365127.344265, Test loss: 20392496000.0
Epoch 265, Train loss: 22709773035.016396, Test loss: 20394649568.0
Epoch 266, Train loss: 23227933225.96721, Test loss: 20392062240.0
Epoch 267, Train loss: 24610999287.60656, Test loss: 20327287904.0
Epoch 268, Train loss: 23022742179.672123, Test loss: 20409407936.0
Epoch 269, Train loss: 22716088928.52459, Test loss: 20448611200.0
Epoch 270, Train loss: 24548563548.32787, Test loss: 20409584608.0
Epoch 271, Train loss: 22709456944.262295, Test loss: 20490219744.0
Epoch 272, Train loss: 22722139843.14754, Test loss: 20439410912.0
Epoch 273, Train loss: 22681278749.377045, Test loss: 20772652832.0
Epoch 274, Train loss: 22909178764.59016, Test loss: 20401764256.0
Epoch 275, Train loss: 22801368424.918037, Test loss: 20534713088.0
Epoch 276, Train loss: 22728392561.311478, Test loss: 20388824544.0
Epoch 277, Train loss: 22588980314.229507, Test loss: 20870223040.0
Epoch 278, Train loss: 22797499459.147537, Test loss: 20378908352.0
Epoch 279, Train loss: 22639693198.688522, Test loss: 20517143936.0
Epoch 280, Train loss: 22574906932.459023, Test loss: 20888651360.0
Epoch 281, Train loss: 22647688292.72131, Test loss: 20511867584.0
Epoch 282, Train loss: 22662426380.590164, Test loss: 20501860736.0
Epoch 283, Train loss: 22624746086.81968, Test loss: 20606888064.0
Epoch 284, Train loss: 22620659682.62295, Test loss: 20365978944.0
Epoch 285, Train loss: 22653271430.295082, Test loss: 20400487552.0
Epoch 286, Train loss: 22842591215.213108, Test loss: 20314412736.0
Epoch 287, Train loss: 22664503799.606564, Test loss: 20345951232.0
Epoch 288, Train loss: 22871327508.98361, Test loss: 20847976736.0
Epoch 289, Train loss: 22704029005.639336, Test loss: 20306627296.0
Epoch 290, Train loss: 22573533035.016396, Test loss: 20306116448.0
Epoch 291, Train loss: 22671118868.98361, Test loss: 20546093632.0
Epoch 292, Train loss: 23589947744.52459, Test loss: 20569191392.0
Epoch 293, Train loss: 22938095460.721317, Test loss: 20480000224.0
Epoch 294, Train loss: 22553762742.55738, Test loss: 20571914976.0
Epoch 295, Train loss: 22619833734.29508, Test loss: 20243961440.0
Epoch 296, Train loss: 22625760491.016384, Test loss: 20422814624.0
Epoch 297, Train loss: 22622210967.081966, Test loss: 20359899456.0

Mean squared error:  20223530206.41655
Root mean squared error:  142209.45892034238
R squared:  -0.014974589751816314

In [ ]:
# save the model
import joblib

joblib.dump(model, "trained_models/nn_model.pkl")